export const GET_NEWS = "GET_NEWS"
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_FAILED = "GET_NEWS_FAILED"

export const POST_PREFERENCE = "POST_PREFERENCE"
export const POST_PREFERENCE_SUCCESS = "POST_PREFERENCE_SUCCESS"

export const SHOW_LOADING_COMPONENT = "SHOW_LOADING_COMPONENT"
export const HIDE_LOADING_COMPONENT = "HIDE_LOADING_COMPONENT"

export const SHOW_LOADING_BTN = "SHOW_LOADING_BTN"
export const HIDE_LOADING_BTN = "HIDE_LOADING_BTN"